global:
  scrape_interval: 15s
  external_labels:
    monitor: 'codelab-monitor'

scrape_configs:
  - job_name: 'httpx'
    scrape_interval: 5s  # Override global scrape interval for this job
    static_configs:
      - targets: ['localhost:8000']  # Example target for HTTP endpoint
