name: publish
on: workflow_dispatch

permissions:
  contents: write

jobs:
  pypi-publish:
    name: upload release to PyPI
    runs-on: ubuntu-latest

    env:
      HTTPX_METRICS_PYPI: ${{ secrets.HTTPX_METRICS_MYPY }}

    steps:
      - uses: "actions/checkout@v4"
      - uses: "actions/setup-python@v5"
        with:
          python-version: 3.8
      - name: "Install dependencies"
        run: "pip install -r requirements.txt"
      - name: "Build"
        run: "hatch build"
      - name: "Publish"
        run: "./scripts/publish"
